### ISSUE TITLE
Fatal Exception: java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by scottlahay** [mcxiaoke/android-volley#130]
Fatal Exception: java.lang.NegativeArraySizeException: -818
       at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:321)
       at com.android.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:117)
       at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:100)

On version  'com.mcxiaoke.volley:library:1.0.6@aar'

**Comment by joebowbeer** [comment]
A fix for this was released in v1.0.16:

https://github.com/mcxiaoke/android-volley/pull/38

**Comment by scottlahay** [comment]
Cool, thanks Joe
