### ISSUE TITLE
NullPointerException with ImageRequest

### ISSUE THREAD

**Issue by mstrengis** [mcxiaoke/android-volley#35]
Here is my stacktrace can't reporduce it on my devices though :(

java.lang.NullPointerException
	at android.graphics.Bitmap.createBitmap(Bitmap.java:622)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:487)
	at com.android.volley.toolbox.ImageRequest.doParse(ImageRequest.java:169)
	at com.android.volley.toolbox.ImageRequest.parseNetworkResponse(ImageRequest.java:126)
	at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:118)

Is there a workaround or this need to be fixed in library ?

**Comment by mstrengis** [comment]
Here is another stacktrace propably related 

java.lang.NegativeArraySizeException: -554
	at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:322)
	at com.android.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:118)
	at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:100)

**Comment by espiegel** [comment]
@mstrengis The second error was fixed and merged here: https://github.com/mcxiaoke/android-volley/issues/37

**Comment by mstrengis** [comment]
thanks @espiegel

**Comment by mcxiaoke** [comment]
close this.
