### ISSUE TITLE
NullPointerException in ExecutorDelivery

### ISSUE THREAD

**Issue by espiegel** [mcxiaoke/android-volley#48]
I just got this crash stack trace from our app in production:

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.volley.Response.isSuccess()' on a null object reference
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:98)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

Perhaps we should protect mResponse and mRequest with a null check first?

**Comment by leoganda** [comment]
I got the same issue. +1

**Comment by yishai-glide** [comment]
this is Volley code, you are returning null in your parseNetworkResponse method

**Comment by mcxiaoke** [comment]
@espiegel mResponse is returned by your own Request instance, you should check parseNetworkResponse method in your request.
