### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by acampayo** [mcxiaoke/android-volley#68]
I'm trying to get a big JSON from a backend using Volley. I'm using a JsonObjectRequest and a singleton Volley request queue to do it. This my source:

```
JsonObjectRequest request = new JsonObjectRequest(Request.Method.GET,
                URL, new Response.Listener<JSONObject>() {
            @Override
            public void onResponse(JSONObject response) {
                apiResponse.response(response, null);
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {    
                apiResponse.response(null, error);
            }
        });
        mRequestQueue.add(request);
```

But always I get this Exception:

```
java.lang.OutOfMemoryError
        at java.util.HashMap.makeTable(HashMap.java:569)
        at java.util.HashMap.doubleCapacity(HashMap.java:589)
        at java.util.HashMap.put(HashMap.java:419)
        at org.json.JSONObject.put(JSONObject.java:263)
        at org.json.JSONTokener.readObject(JSONTokener.java:385)
        at org.json.JSONTokener.nextValue(JSONTokener.java:100)
        at org.json.JSONTokener.readArray(JSONTokener.java:430)
        at org.json.JSONTokener.nextValue(JSONTokener.java:103)
        at org.json.JSONTokener.readObject(JSONTokener.java:385)
        at org.json.JSONTokener.nextValue(JSONTokener.java:100)
        at org.json.JSONObject.<init>(JSONObject.java:155)
        at org.json.JSONObject.<init>(JSONObject.java:172)
        at com.android.volley.toolbox.JsonObjectRequest.parseNetworkResponse(JsonObjectRequest.java:103)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:123)
```

Do you have any idea why it's crashing? Could it be related to the big size of my JSON response?

**Comment by Sairaj4522** [comment]
Hey, may be this problem you have is because Volley was never implemented to collect big data

**Comment by Sairaj4522** [comment]
Check out this link http://stackoverflow.com/questions/31356972/android-volley-java-lang-outofmemoryerror

**Comment by mcxiaoke** [comment]
@acampayo you should cancel all requests and stop queue in onDestroy method, and using latest version 1.0.17 may has some help.
